### PR TITLE
PS3 Memory Card Adaptor support (as well as bumping the requirements to .NET 4.5)

### PR DESCRIPTION
**Pull request by nzgamer41**
Added PS3MCA support, thanks to https://github.com/paolo-caroni/ps3mca-ps1 for the initial work done on getting it working with libusb and documenting it, this version uses LibUsbDotNet which required .NET Framework 4.5 minimum hence the version change. I also could not get it to work right with a 64 bit version of libusb-1.0.dll so I changed it to prefer 32-bit. Maybe worth someone else testing before this is merged, it worked fine for me on Windows 10 20H2 with my official Sony adaptor (CECHZM1)

### CODE REVIEW

**Comment by nzgamer41** [comment]
Didn't realize there's actually already a fork that was working on PS3MCA support, maybe worth @ndepoel having a look and seeing if his implementation is better (I wrote mine in 8 hours ish)

**Comment by ndepoel** [comment]
Thanks for the ping. My implementation was also pretty quick and dirty, mostly made for personal use, and since it's a pretty straightforward thing to implement I don't expect there will be much variation in quality.

The biggest challenge I found in practice was finding a compatible libusb driver for Windows that didn't require jumping through a ton of hoops to install. Last year while reviewing this project I found that Zadig is a very useful tool for generating a driver and installing it with a very simple clicks. I see you already found out the same, though I documented it with a bit more detail in the README of my fork. You may find some added value in merging that documentation.

**Comment by ndepoel** [comment]
By the way, the reason why I never submitted any pull requests before was that just as I had finished my initial implementation, @ShendoXT started working on a major overhaul and refactoring of their code, which made my changes incompatible. Additionally, it was difficult to justify the inclusion of PS3MCA support when the driver installation was as cumbersome as it was at the time. That has changed in the meantime with the appearance of Zadig.

**Comment by ShendoXT** [comment]
Thank you both for implementing this feature to MemcardRex.
I actually got the adapter fairly recently so I'm glad for this and happy that I'm also able to use it myself.

I'm having some issues however when testing it. Reading works fine but writing has some issues.
After writing is done or nearing the end I get this exception.

ps3mca_error

Have you encountered this issue?

**Comment by ShendoXT** [comment]
@ndepoel I also tried your implementation and it seems to work without issues as far as I can tell.
I also noticed you took different approach and used WinUSB driver.
With this approach only LibUsbDotNet.dll is needed as far as I can tell which leads to less dependencies.

@nzgamer41 I noticed that your implementation is faster then @ndepoel when reading or writing but his code uses 50ms
sleeps in order to wait for frames to be written. Might be related to data corruption or above mentioned errors.

@ndepoel GitHub complains that there is a merge conflict but can you please make pull request regardless?

**Comment by ndepoel** [comment]
@ShendoXT Done. I have already fixed the merge conflicts with your changes to make your life a bit easier. 

The 50 ms sleeps are a result of my implementation being a direct port of Orion's PS3mca-PS1mc tool, which included the sleeps. They are likely there to improve the reliability, but I've never tested with other values to verify that. It might be possible to make it faster without sacrificing reliability.

**Comment by nzgamer41** [comment]
Hi, I occasionally got that issue when writing, I'm not entirely sure
what's causing it other then perhaps a memory bug in Libusbdotnet, out of
curiosity do aftermarket ps1 cards work for you? I have one branded
Memory30 that I believe is 2 memory cards in one (pressing L1 R1 L2 R2 at
the same time turns a light on on the card and switches memory cards only
on a PS1) and it won't read right with the ps3mca, I don't have a dexdrive
or carduino thing to try but that could either be my memory card or the
reader.

Most of the time with Sony cards itd read and write fine for me.

**Comment by nzgamer41** [comment]
> Edit: Hm... This error seems to occur at random as far as I can tell.
> I also noticed that I get corrupted data upon reading sometimes. I'm using official Sony SCPH-1020 Memory Card.

I get corrupted data if the card isn't connected right (ie dirty contacts etc)

**Comment by ShendoXT** [comment]
@nzgamer41 Thank you for taking the time to implement this feature to MemcardRex and also informing me about the @ndepoel 's implementation as well.
I decided to merge his version because according to my tests it's more reliable.

No hard feelings I hope :)

**Comment by nzgamer41** [comment]
Meh, I'm happy this is a feature in mainline either way! More ways to manage saves/install FreePSXBoot (what piqued my interest originally) is awesome either way

**Pull request closed without merging**
